### ISSUE TITLE
Split cozy-light in several files

### ISSUE THREAD

**Issue by frankrousseau** [cozy-labs/cozy-light#34]
The main file is too big and too hard to understand. The main file should be splitted in many files. Then we should try to remove code or features.

**Comment by maboiteaspam** [comment]
Now it works. Seems satisfying. I need to do more manual tests and usages to ensure it all good to me, but so far, at least, the test suite pass.
https://travis-ci.org/maboiteaspam/cozy-light/builds/45970468
It is also missing the recent commits.

**Comment by frankrousseau** [comment]
Because it's a big refactoring, I think I will wait for the week-end for a full review.

**Comment by maboiteaspam** [comment]
yeah sure, not a hurry and not 100% ready to merge yet.

**Comment by frankrousseau** [comment]
Done!
