### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by maboiteaspam** [cozy-labs/cozy-light#56]
Hi,

Small thing i'd like talk about,

in the core code we can find many
```
        if (callback !== undefined && typeof(callback) === 'function') {
          callback();
        }
```

How about moving that to nodeHelper as 
```
call:function(cb,args1,args2,argsN){
        if (cb !== undefined && typeof(cb) === 'function') {
          cb.apply(null,arguments);
        }
}
```

Also, i see now we do this,
```
        if (configHelpers.mainWatcher !== undefined) {
          configWatcher.one(callback);
        }
```

I think we figure out the same problem. Except that i understood that as a lack of status representation internally.
I mean that internally, we don t keep track of the current status (started, stopped, restarting), neither about current action such install / uninstall-app etc.
Thing is nothing prevent to enter in weird behavior if twice of those events occurs together.

Downside is the extra code to support that, but seems like somehow it has to be managed, as of this new code shown.

Loking for some thoughts.

**Comment by frankrousseau** [comment]
Let's say it's done.
