### ISSUE TITLE
cozy-light install-distro personal-cloud failed

### ISSUE THREAD

**Issue by markh8888** [cozy-labs/cozy-light#64]
Running 'cozy-light install-distro personal-cloud' and failed with:

# cozy-light install-distro personal-cloud
info - Cozy Light | Start distribution installation for personal-cloud
info - Distros | Installing plugins...
info - Cozy Light | Installing plugin cozy-labs/cozy-light-simple-dashboard...
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/cozy-labs/cozy-light-simple-dashboard) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/cozy-labs/cozy-light-simple-dashboard) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:cozy-labs/cozy-light-simple-dashboard) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:cozy-labs/cozy-light-simple-dashboard) undefined
npm ERR! git clone git@github.com:cozy-labs/cozy-light-simple-dashboard undefined
npm ERR! git clone git@github.com:cozy-labs/cozy-light-simple-dashboard undefined
{ [Error: not found: git] code: 'ENOGIT' }
error - Cozy Light | Cannot find given plugin manifest.
error - Cozy Light | Make sure it lives on Github
error - Cozy Light | or in the given directory.
error - Cozy Light | cozy-labs/cozy-light-simple-dashboard installation failed.
not found: git
error - Cozy Light | An error occured while installing your distribution

Anyone has the same issue?

**Comment by frankrousseau** [comment]
HI @markh8888. It looks like you have a problem with your Git installation. On which OS are you running it?

**Comment by maboiteaspam** [comment]
@markh8888 , yes seems you do not have GIT setup on your machine. Please check https://github.com/cozy-labs/cozy-light#install

**Comment by markh8888** [comment]
Got it. git is not in the PATH. Works now, Thanks.

**Comment by frankrousseau** [comment]
Great! @markh8888 I have a question: on which hardware do you run it?

By the way, that would be awesome if you share your feedback of Cozy Light here or on the Cozy forum: http://forum.cozy.io

PS: Thx @maboiteaspam for the help!

**Comment by markh8888** [comment]
Running on a PC Engines apu system board (AMD G series T40E CPU) with 64bit Linux customized from "Linux from Scratch". 

--------------------------------------------
On Thu, 1/15/15, Frank Rousseau <notifications@github.com> wrote:

 Subject: Re: [cozy-light] cozy-light install-distro personal-cloud failed (#64)
 To: "cozy-labs/cozy-light" <cozy-light@noreply.github.com>
 Cc: "markh8888" <markh8888@yahoo.com>
 Date: Thursday, January 15, 2015, 7:10 AM
 
 Great! @markh8888 I have a
 question: on which hardware do you run it?
 
 By the way, that would be awesome if you share your
 feedback of Cozy Light here or on the Cozy forum: http://forum.cozy.io
 
 PS: Thx @maboiteaspam for the
 help!
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by frankrousseau** [comment]
Ok thx @markh8888.
