### ISSUE TITLE
Multiple users?

### ISSUE THREAD

**Issue by runvnc** [cozy-labs/cozy-light#74]
Hello, is it possible to have multiple users, or is this planned?  For example if one house were sharing a personal server, maybe one of the people would need some setting or something different from the other (like a different name or email).

Or is that something that is handled individually by each app?

**Comment by frankrousseau** [comment]
In fact you can start two Cozy Light. One for each user. For that you have two options :

* run it with two separated Linux users.
* run it by changing the parameters home.

And whatever way you chose, you will have to change the port via an option too.

Example:

    cozy-light start -p 19504 -h /home/unixuser/user-2

**Comment by maboiteaspam** [comment]
is database consuming a port number that would be a conflict that admin can t fix.

**Comment by runvnc** [comment]
Thanks.
